# Generated by Django 4.2.1 on 2023-05-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='STUDENT', max_length=15),
        ),
    ]
